import React from "react";

import ABOUT_US from "./ABOUT_US/ABOUT_US";
import ADVANCE_PACKING from "./ADVANCE_PACKING/ADVANCE_PACKING";
import HERO from "./HERO/HERO";
import EXCLUSIVE_GIFT_BOXES from "./EXCLUSIVE_GIFT_BOXES/EXCLUSIVE_GIFT_BOXES";

export default { ABOUT_US, EXCLUSIVE_GIFT_BOXES, ADVANCE_PACKING, HERO };
